# Automates creation of Release Drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
name: 448 Version Action
run-name: Building HPI of 448 Version
on:
  push:
    branches:
      - "448"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml -DskipTests
    - uses: actions/upload-artifact@v3
      with:
        name: 448-HPI
        path: target/*.hpi
  
  
